@echo off
echo Инициализация репозитория (или проверка существующего)...
git init

echo Добавление всех файлов в индекс...
git add .

echo Создание коммита...
git commit -m "Изменение страниц"

echo Переключение/переименование ветки на main...
git branch -M main

echo Добавление удаленного репозитория origin (может выдать ошибку, если уже существует)...
git remote add origin https://github.com/alley-wiki/alley-wiki.github.io.git

echo Отправка изменений на GitHub (ветка main)...
git push -u origin main

echo.
echo Готово! Нажмите любую клавишу для выхода...
pause